" Generated by vim-plug
" Sat 29 Oct 2022 01:52:50 PM BST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['any-jump.vim'].commit = '6ec5f8a71a07ab89f751ef1186efb3d4143e676e'
silent! let g:plugs['ctrlp.vim'].commit = '8b4a9523632049b3b373de1233bef346073b8982'
silent! let g:plugs['editorconfig-vim'].commit = 'd354117b72b3b43b75a29b8e816c0f91af10efe9'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['traces.vim'].commit = '9663fcf84de5776bee71b6c816c25ccb6ea11d1a'
silent! let g:plugs['vim-airline'].commit = '0ed7b8bb2ed68d65a5ba55317896680b31d315b0'
silent! let g:plugs['vim-airline-themes'].commit = 'cc5d3490c8f4c87d29d97df414941a9df8ceb390'
silent! let g:plugs['vim-auto-save'].commit = '2e3e54ea4c0fc946c21b0a4ee4c1c295ba736ee8'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a' silent! let g:plugs['vim-signify'].commit = '8bc268c79d4053c2f5ccaadcf0b666dd16ed3a58'
silent! let g:plugs['vim-snippets'].commit = 'b47c2e37237875185d170f32cac67af5ab72f22d'
silent! let g:plugs['vim-solarized8'].commit = '9f9b7951975012ce51766356c7c28ba56294f9e8'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-which-key'].commit = '9875baefb1d3e78abbf8f652a17e130744a37742'

" Remember to make this silent to prevent it from stopping Vim from opening
silent! PlugUpdate!

