" Generated by vim-plug
" Wed 13 Jul 2022 09:18:23 PM BST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['any-jump.vim'].commit = '67b17372342826355c015427a5cdbda7c5d3e3b9'
silent! let g:plugs['ctrlp.vim'].commit = '3ce448c9687ae96dea0caf4da388ecd8d9072f72'
silent! let g:plugs['editorconfig-vim'].commit = 'd354117b72b3b43b75a29b8e816c0f91af10efe9'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['traces.vim'].commit = '9663fcf84de5776bee71b6c816c25ccb6ea11d1a'
silent! let g:plugs['vim-airline'].commit = 'ebb89a0846ff8b8bc64579155d661b825f97d3f2'
silent! let g:plugs['vim-airline-themes'].commit = '55bad92d246a31e3425dfaf16b7eec657eab1fad'
silent! let g:plugs['vim-auto-save'].commit = 'd8ff037621e2351278cf0892ca19ee7ce479e802'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-signify'].commit = '69498f6d49f3eeac06870012416dd9bf867b84f3'
silent! let g:plugs['vim-snippets'].commit = '222cf7b44bb569c9a046a9891000c898bd4c43c9'
silent! let g:plugs['vim-solarized8'].commit = '9f9b7951975012ce51766356c7c28ba56294f9e8'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-which-key'].commit = '654dfc15cf86946e7e70d12cf095bf55002d93a5'

" Remember to make this silent to prevent it from stopping Vim from opening
silent! PlugUpdate!

