" Generated by vim-plug
" Sat 22 Jan 2022 11:12:58 PM GMT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['any-jump.vim'].commit = '67b17372342826355c015427a5cdbda7c5d3e3b9'
silent! let g:plugs['ctrlp.vim'].commit = 'ed04d2ec91c78748f0d8ddf69df2f6e5cffa7bb8'
silent! let g:plugs['editorconfig-vim'].commit = 'a8e3e66deefb6122f476c27cee505aaae93f7109'
silent! let g:plugs['nerdtree'].commit = 'eed488b1cd1867bd25f19f90e10440c5cc7d6424'
silent! let g:plugs['traces.vim'].commit = '803d97786d0fbe95d33fe3c69e213518ea296839'
silent! let g:plugs['vim-airline'].commit = '95935e66b9a3cd802900ac2d23ccaaf70145d857'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-auto-save'].commit = 'd8ff037621e2351278cf0892ca19ee7ce479e802'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-signify'].commit = '69498f6d49f3eeac06870012416dd9bf867b84f3'
silent! let g:plugs['vim-snippets'].commit = 'cbad57e5d0304198503648b5416ea28d2d1d437a'
silent! let g:plugs['vim-solarized8'].commit = '28b81a4263054f9584a98f94cca3e42815d44725'
silent! let g:plugs['vim-surround'].commit = 'aeb933272e72617f7c4d35e1f003be16836b948d'
silent! let g:plugs['vim-which-key'].commit = '165772f440bd26c4679eef8b8b493ab11fffc4ae'

" Remember to make this silent to prevent it from stopping Vim from opening
silent! PlugUpdate!

