# GnuPG credential agent

default-cache-ttl 86400
default-cache-ttl-ssh 86400
max-cache-ttl 999999
enable-ssh-support

# Generic
#pinentry-program /usr/bin/pinentry

# Terminal
#pinentry-program /usr/bin/pinentry-tty
#pinentry-program /usr/bin/pinentry-curses
#pinentry-program /usr/local/bin/pinentry-curses

# Linux GUI
#pinentry-program /usr/bin/pinentry-emacs
#pinentry-program /usr/bin/pinentry-gtk
#pinentry-program /usr/bin/pinentry-gtk-2
#pinentry-program /usr/bin/pinentry-gtk-3
#pinentry-program /usr/bin/pinentry-gnome3
#pinentry-program /usr/bin/pinentry-qt
#pinentry-program /usr/bin/pinentry-qt5

# MacOS Homebrew GUI
#pinentry-program /usr/local/bin/pinentry-mac
#pinentry-program /usr/local/bin/pinentry-osx

# Windows GUI
#pinentry-program "C:\Program Files (x86)\GnuPG\bin\pinentry.exe"
#pinentry-program "C:\Program Files\GnuPG\bin\pinentry.exe"
