#!/usr/bin/env sh
###############################################################################
# Perform logout operations for all Posix compatible shells supporting it.
# Must be Posix shell compatible.

###############################################################################
# Logout operations
# Kill agents
if [ -n "$SSH_AUTH_SOCK" -a "$SHLVL" = 1 ]; then
  eval $(ssh-agent -k) >/dev/null
fi

# Load application specific logout files
if [ $(find "${XDG_CONFIG_HOME:-$HOME/.config}/" \
        -mindepth 1 -maxdepth 1 2>/dev/null | wc -l) != 0 ]
then
  for p in "${XDG_CONFIG_HOME:-$HOME/.config}"/*; do
    try_source "${p}/.logout"
  done
fi

# Local installation overrides
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/custom.logout"

