#!/usr/bin/env sh
###############################################################################
# Perform setup for login sh shells.
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

# Local installation overrides
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/sh/custom.login"

