#! /usr/bin/env bash
install_packages() {
  set -x
  sudo apt update -y && sudo apt-get upgrade -y
  sudo apt install stow vim emacs25 git clang-tidy clang-format \
                   tmux gcc clang ninja-build cmake meson make  \
                   silversearcher-ag autoconf automake xorg     \
                   bash htop linux-perf python doxygen rsync    \
                   binutils nasm g++ curl wget tree docker      \
                   rxvt-unicode-256color -y
  set +x
}

install_packages

