#! /usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

install_package_sources() {
  return
}

uninstall_package_sources() {
  return
}

install_packages() {
  echo "Installing debian generic packages..."
  sudo apt-get update -y >/dev/null && sudo apt-get upgrade -y >/dev/null
  PKGS_TO_INSTALL=$(cat ${SCRIPT_DIR}/all-pkg-list | tr '\n' ' ')
  echo "Attempting to install: ${PKGS_TO_INSTALL[@]}"
  sudo apt-get install ${PKGS_TO_INSTALL[@]} -y >/dev/null
  [[ $? ]] && echo "Done!" || echo "Failed!"
}

uninstall_package_sources
install_package_sources
install_packages

