#! /usr/bin/env bash

install_package_sources() {
  set -x
  sudo mkdir -p /etc/apt/sources.list.d/
  if [[ ! -e /etc/apt/sources.list.d/stretch-backports.list ]]; then
    sudo bash -c 'echo "deb http://deb.debian.org/debian stretch-backports main" \
      >/etc/apt/sources.list.d/stretch-backports.list'
  fi
  set +x
}

uninstall_package_sources() {
  set -x
  if [[ -e /etc/apt/sources.list.d/stretch-backports.list ]]; then
    sudo rm -f /etc/apt/sources.list.d/stretch-backports.list
  fi
  set +x
}

install_packages() {
  # None yet
  return
}

uninstall_package_sources
install_package_sources
install_packages

