#! /usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

install_package_sources() {
  if [[ ! -e /etc/apt/sources.list.d/stretch-backports.list ]]; then
    echo "Adding stretch-backports to sources..."
    sudo mkdir -p /etc/apt/sources.list.d/
    sudo bash -c 'echo "deb http://deb.debian.org/debian stretch-backports main" \
      >/etc/apt/sources.list.d/stretch-backports.list'
  fi
}

uninstall_package_sources() {
  if [[ -e /etc/apt/sources.list.d/stretch-backports.list ]]; then
    echo "Removing stretch-backports from sources..."
    sudo rm -f /etc/apt/sources.list.d/stretch-backports.list
  fi
}

install_packages() {
  echo "Installing stretch specific packages..."
  return
}

uninstall_package_sources
install_package_sources
install_packages

