#!/usr/bin/env bash
###############################################################################
# Perform configuration for all interactive bash shells
require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

###############################################################################
# Setup environment variables
# Colors and PS1 setup - for now this is largely shared between shells
if [ $(id -u) -eq 0 ]; then
  # Special root PS1 colors
  color_shell="$(text_fg_color 10)"
  color_path="$(text_fg_color 10)"
  color_git="$(text_fg_color 10)"
  color_separator="$(text_fg_color cyan)"
  color_reset="$(text_reset)"
else
  # PS1 for other users
  color_shell="$(text_fg_color 10)"
  color_path="$(text_fg_color red)"
  color_git="$(text_fg_color blue)"
  color_separator="$(text_fg_color cyan)"
  color_reset="$(text_reset)"
fi

# We escape the lengths of the colors via \[\] here rather than the color
# definitions above, as Bash seems to struggle if we don't
PS1="\[$(text_reset)\]\[${color_shell}\][\$(whoami)@\$(hostname):bash]"
PS1+="\[${color_path}\]<\$(basename \${PWD})/>" # Path
PS1+="\[${color_git}\]\$(get_vcs_branch)" # VCS branch
PS1+="\[${color_separator}\]λ " # Separator
PS1+="\[${color_reset}\]" # Color back to normal
unset color_shell color_path color_git color_separator color_reset

# Place the history in cache
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history-$HOSTNAME-$USER"
# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth:erasedups
# For setting history length
HISTSIZE=10000
HISTFILESIZE=$HISTSIZE
# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS
shopt -s checkwinsize

# Enable programmable completion features (you don't need to enable
# this if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

reload_dotfiles() {
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/env"
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/login"
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/interactive"
}

# Local installation overrides
load_override_module bash interactive

