#!/usr/bin/env bash
###############################################################################
# Perform configuration for all login bash shells
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

# Grab user bash-completion scripts from $XDG_CONFIG_HOME
assign_export BASH_COMPLETION_USER_FILE \
  "${XDG_CONFIG_HOME:-$HOME/.config}/bash-completion/bash_completion"
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash-completion/bash_completion"

silence_output assert_directory "${XDG_CACHE_HOME:-$HOME/.cache}/bash"

# Local installation overrides
load_override_module bash login

