#!/usr/bin/env bash
###############################################################################
# Perform actions required on logout for login bash shells
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/logout"

# Local installation overrides
load_override_module bash logout

