#!/usr/bin/env ksh
###############################################################################
# Perform setup for login ksh shells.
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

if [ ! -d  "${XDG_DATA_HOME:-$HOME/.local/share}/ksh" ]; then
  mkdir "${XDG_DATA_HOME:-$HOME/.local/share}/ksh"
fi

# Local installation overrides
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/ksh/custom.login"

