#!/usr/bin/env bash
###############################################################################
# Perform configuration for all interactive bash shells
. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

###############################################################################
# Setup environment variables
# Colors and PS1 setup - for now this is largely shared between shells
if [ $(id -u) -eq 0 ]; then
  # Special root PS1 colors
  color_shell=10
  color_path=10
  color_git=10
  color_separator=6
else
  # PS1 for other users
  color_shell=10
  color_path=1
  color_git=4
  color_separator=6
fi
# Add a convenient shell name identifier
PS1="\[$(tput setaf $color_shell)\][\$(whoami)@\$(hostname):bash]"
PS1+="\[$(tput setaf $color_path)\]<\$(basename \${PWD})/>" # Path
PS1+="\[$(tput setaf $color_git)\]\$(get_vcs_branch)" # VCS branch
PS1+="\[$(tput setaf $color_separator)\]λ " # Separator
PS1+="\[$(tput sgr0)\]" # Color back to normal
unset color_shell color_path color_git color_separator

# Place the history in cache
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history-$HOST-$USER"
# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth:erasedups
# For setting history length
HISTSIZE=10000
HISTFILESIZE=$HISTSIZE
# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS
shopt -s checkwinsize

# Enable programmable completion features (you don't need to enable
# this if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

reload_dotfiles() {
  . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/env"
  . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/login"
  . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/interactive"
}

# Local installation overrides
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/custom.interactive"

