#!/usr/bin/env ksh
###############################################################################
# Perform setup for interactive ksh shells.
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive"

# Colors and PS1 setup - for now this is largely shared between shells
# Tramp and other dumb terminals require a more ordinary prompt
if [ "$TERM" = "dumb" ]; then
    PS1="$ "
    PS2='> '
    PS3='#? '
    PS4='+ '
else
  color_reset="$(text_reset)"
  if [ "$(id -u)" -eq 0 ]; then
    # Special root PS1 colors
    fg_shell="$(text_fg_color 10)"
    fg_path="$(text_fg_color 10)"
    fg_git="$(text_fg_color 10)"
    fg_separator="$(text_fg_color cyan)"
  else
    # PS1 for other users
    fg_shell="$(text_fg_color 10)"
    fg_path="$(text_fg_color red)"
    fg_git="$(text_fg_color blue)"
    fg_separator="$(text_fg_color cyan)"
  fi

  PS1="${color_reset}${fg_shell}[\$(whoami)@\$(hostname):ksh]"
  PS1+="${fg_path}<\$(basename \"\${PWD}\")/>" # Path
  PS1+="${fg_git}\$(get_vcs_branch)" # VCS branch
  PS1+="${fg_separator}λ " # Separator
  PS1+="${color_reset}" # Color back to normal
  PS2="${fg_separator}> ${color_reset}"
  PS3="${fg_separator}#? ${color_reset}"
  PS4="${fg_separator}+ ${color_reset}"
fi

# Place the history in state
HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/ksh/history"
HISTSIZE=10000

# Default to Emacs keybindings
set -o emacs

reload_dotfiles() {
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/ksh/env"
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/ksh/login"
  require_source "${XDG_CONFIG_HOME:-$HOME/.config}/ksh/interactive"
}

# Load shell specific interactive modules
load_per_application_modules interactive ksh

