#!/usr/bin/env ksh
###############################################################################
# Perform setup for login ksh shells.
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

silence_output assert_directory "${XDG_CACHE_HOME:-$HOME/.cache}/ksh"
silence_output assert_directory "${XDG_STATE_HOME:-$HOME/.local/state}/ksh"

# Load shell specific login modules
load_per_application_modules login ksh

