#!/usr/bin/env ksh
###############################################################################
# Perform actions required on logout for login sh shells
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/logout"

# Load shell specific logout modules
load_per_application_modules logout ksh

