#!/usr/bin/env zsh
###############################################################################
# Perform configuration for all login zsh shells
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

require_source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

silence_output assert_directory "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
silence_output assert_directory "${XDG_STATE_HOME:-$HOME/.local/state}/zsh"

# Local installation overrides
load_override_module zsh login

