#!/usr/bin/env zsh
###############################################################################
# Perform configuration for all login zsh shells
# Shouldn't need much if any further configuration beyond the shared
# configuration present in $XDG_CONFIG_HOME/shell/.

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login"

if [ ! -d  "${XDG_CACHE_HOME:-$HOME/.cache}/zsh" ]; then
  mkdir "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
fi

# Local installation overrides
try_source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/custom.login"

