scriptencoding utf-8
set encoding=utf8
set nocompatible
filetype indent plugin on
syntax on

if !empty($XDG_CONFIG_HOME)
  let g:vim_cfg_dir=expand('$XDG_CONFIG_HOME/vim/')
else
  let g:vim_cfg_dir=expand('$HOME/.config/vim/')
endif
if !empty($XDG_CACHE_HOME)
  let g:vim_cache_dir=expand('$XDG_CACHE_HOME/vim/')
else
  let g:vim_cache_dir=expand('$HOME/.cache/vim/')
endif

" Must be first
execute 'source ' . expand(g:vim_cfg_dir . 'plugins.vim')

" All the settings changes
execute 'source ' . expand(g:vim_cfg_dir . 'general.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'colour.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'bindings.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'ctrlp.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'airline.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'ultisnips.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'nerdtree.vim')
execute 'source ' . expand(g:vim_cfg_dir . 'anyjump.vim')

" Load a user-defined custom overrides file if it exists
if filereadable(expand('$XDG_CONFIG_HOME/vim/vimrc.local'))
  source expand('$XDG_CONFIG_HOME/vim/vimrc.local')
endif

