#!/usr/bin/env sh
###############################################################################
# Perform login operations for all Posix compatible shells supporting it.
# Must be Posix shell compatible.

###############################################################################

# Manually load environment.d user-global environment variables if systemd is
# not present or we are running under a TTY. If we're running under a TTY then
# we want to fresh load all the environment variables on each login shell (in
# order to make the initial login shell work properly if dependent on these
# variables, as the systemd user session appears to be loaded *after* the
# initial shell)
if ! has_systemd || is_session tty; then
  silence_output load_user_systemd_environment_d
fi

# Making sure the current directory isn't in PATH for security & weirdness
# reasons.
path_remove . PATH
path_remove "" PATH

# Load shared shell specific login modules
load_per_application_modules login shell

