#!/usr/bin/env sh
###############################################################################
# Perform logout operations for all Posix compatible shells supporting it.
# Must be Posix shell compatible.

###############################################################################

# Load shared shell specific logout modules
load_per_application_modules logout shell
