#!/usr/bin/env sh
###############################################################################
# Perform logout operations for all Posix compatible shells supporting it.
# Must be Posix shell compatible.

###############################################################################

# Load application specific logout files
load_per_application_modules logout

# Local installation overrides
load_override_module shell logout

