#! /usr/bin/env bash

[[ -f $HOME/.bash_aliases ]] && . $HOME/.bash_aliases

if [ -x /usr/bin/dircolors ]; then
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias l.='ls -d .*'

# because I'm clumsy and accidentally delete stuff
alias rm='rm -iI --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

alias h='history'
alias j='jobs'

alias vi='vim'
alias tmux='tmux -2 -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'

# aliases to quickly do git certificate trust issue workaround
alias git-disable-ssl='GIT_SSL_NO_VERIFY=1 git'
alias git-enable-ssl='GIT_SSL_NO_VERIFY=0 git'

# alias to remove all tracked folders and directories
# from a local git repo's directory
alias git-clean-tracked-files='git ls-files -z | xargs -0 rm'
alias git-clean-tracked-dir='git ls-tree --name-only -d -r -z HEAD \
  | sort -rz \
  | xargs -0 rmdir'
alias git-clean-tracked='git-clean-tracked-files; git-clean-tracked-dir'

# various hardware info
alias cpu-count='nproc --all'
alias meminfo='free -m -l -t'
alias cpuinfo='lscpu'
alias diskinfo='df -H'

