#! /usr/bin/env bash

[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/bash/functions ]] && . ${XDG_CONFIG_HOME:-$HOME/.config}/bash/functions

export ALTERNATE_EDITOR='nano'
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# Doom-emacs variables
export DOOMDIR=${XDG_CONFIG_HOME:-$HOME/.config}/doom
export DOOMLOCALDIR=${XDG_CACHE_HOME:-$HOME/.cache}/emacs

path-update $HOME/.local/bin
# add doom emacs configuration scripts to path
path-update ${XDG_CONFIG_HOME:-$HOME/.config}/emacs/bin

# store the distro name in DISTRO_ vars
if type lsb_release >/dev/null 2>&1; then
  # A modern generic method
  DISTRO_OS=$(lsb_release -si)
  DISTRO_VERSION=$(lsb_release -sr)
  DISTRO_CODENAME=$(lsb_release -sc)
else
  # Fallback
  DISTRO_OS=$(uname -s)
  DISTRO_VERSION=$(uname -r)
  DISTRO_CODENAME=$DISTRO_VERSION
fi
case $(uname -m) in
  x86_64)
    DISTRO_BITS=64
    ;;
  i*86)
    DISTRO_BITS=32
    ;;
  *)
    DISTRO_BITS=?
    ;;
esac

