#!/usr/bin/env bash
# Lots of applications don't respect XDG conventions
# so here are a bunch of hacks to get them working

# Set all the XDG path vars
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
# Shouldn't set this as systemd sets it up
#export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$UID}
export XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg}

# Core system tooling
# This causes dumb issues with client connection to this box
# export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export XINITRC="${XDG_CONFIG_HOME}/X11/xinitrc"
export XSERVERRC="${XDG_CONFIG_HOME}/X11/xserverrc"

# XCompose
export XCOMPOSEFILE="${XDG_CONFIG_HOME}/X11/xcompose"
export XCOMPOSECACHE="${XDG_CACHE_HOME}/X11/xcompose"

# Wget
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
alias wget="wget --hsts-file=\"${XDG_CACHE_HOME}/wget/hsts\""

# GnuPG
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"

# ICEAuthority
export ICEAUTHORITY="${XDG_CACHE_HOME}/ICEauthority"

# Less pager
mkdir -p "${XDG_CACHE_HOME}/less"
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"

# Most pager
export MOST_INITFILE="${XDG_CONFIG_HOME}/mostrc"

# NCurses
export TERMINFO="${XDG_DATA_HOME}/terminfo"
export TERMINFO_DIRS="${XDG_DATA_HOME}/terminfo:/usr/share/terminfo"

# OpenSSL
export RANDFILE="${XDG_CACHE_HOME}/openssl/rnd"

# Readline
export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"

# GNU Screen
export SCREENRC="${XDG_CONFIG_HOME}/screen/screenrc"

# URXVTD (rxvt daemon)
export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvtd"

# SVN
export SUBVERSION_HOME="${XDG_CONFIG_HOME}/subversion"

# Vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/core.vim" | source $MYVIMRC'

# Bash
export HISTFILE="${XDG_DATA_HOME}/bash/history"
export BASH_COMPLETION_USER_FILE="${XDG_CONFIG_HOME}/bash-completion/bash_completion"

# Ack
export ACKRC="${XDG_CACHE_HOME}/ack/ackrc"

# ASpell
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; \
  personal $XDG_CONFIG_HOME/aspell/en.pws; \
  repl $XDG_CONFIG_HOME/aspell/en.prepl"

# Pass
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"


# Programming language tooling
#Python
export PYTHONHISTORY="${XDG_CACHE_HOME}/python/python_history"
# SetupTools
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python-eggs"
# PyLint
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
# Jupyter
export IPYTHONDIR="${XDG_CONFIG_HOME}/jupyter"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"

# Ruby
# IRuby
export IRBRC="${XDG_CONFIG_HOME}/irb/irbrc"
# Ruby Bundle
export BUNDLE_USER_CONFIG="${XDG_CONFIG_HOME}/bundle"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundle"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundle"
# Ruby gems
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"

# Rust
# Cargo
export CARGO_HOME="${XDG_DATA_HOME}/cargo"

# Mathematica
export MATHEMATICA_USERBASE="${XDG_CONFIG_HOME}/mathematica"

# Go
export GOPATH="${XDG_DATA_HOME}/go"

# Javascript
# Node
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node_repl_history"
# NPM
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"

# Racket (PLT Scheme)
export PLTUSERHOME="${XDG_DATA_HOME}/racket"

# Haskell
# Stack
export STACK_ROOT="${XDG_DATA_HOME}/stack"

# Java
# Gradle
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"

# C/C++
# CCache
export CCACHE_CONFIGPATH="${XDG_CONFIG_HOME}/ccache.config"
export CCACHE_DIR="${XDG_CACHE_HOME}/ccache"

# CUDA
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"

# .NET
# NuGet
export NUGET_PACKAGES="${XDG_CACHE_HOME}/NuGetPackages"

# Virtualization
# Docker
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker-machine"
# Vagrant
export VAGRANT_HOME="${XDG_DATA_HOME}/vagrant"
export VAGRANT_ALIAS_FILE="${XDG_DATA_HOME}/vagrant/aliases"

# Cloud
# Azure Python CLI
export AZURE_CONFIG_DIR="${XDG_DATA_HOME}/azure"
# AWS CLI
export AWS_SHARED_CREDENTIALS_FILE="${XDG_CONFIG_HOME}/aws/credentials"
export AWS_CONFIG_FILE="${XDG_CONFIG_HOME}/aws/config"

# Databases
# MySQL
export MYSQL_HISTFILE="${XDG_DATA_HOME}/mysql_history"
# Postgres
mkdir -p "${XDG_CONFIG_HOME}/pg"
mkdir -p "${XDG_CACHE_HOME}/pg"
export PSQLRC="${XDG_CONFIG_HOME}/pg/psqlrc"
export PSQL_HISTORY="${XDG_CACHE_HOME}/pg/psql_history"
export PGPASSFILE="${XDG_CONFIG_HOME}/pg/pgpass"
export PGSERVICEFILE="${XDG_CONFIG_HOME}/pg/pg_service.conf" 


# Desktop Environments
# GTK
export GTK_RC_FILES="${XDG_CONFIG_HOME}/gtk-1.0/gtkrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"

# KDE
export KDEHOME="${XDG_CONFIG_HOME}/kde"


# Misc applications
# MPlayer
export MPLAYER_HOME="${XDG_CONFIG_HOME}/mplayer"

# Mednafen PS1 emulator
export MEDNAFEN_HOME="${XDG_CONFIG_HOME}/mednafen"

# Atom text editor
export ATOM_HOME="${XDG_DATA_HOME}/atom"

# WINE
mkdir -p "${XDG_DATA_HOME}/wineprefixes"
export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/default"

