#!/usr/bin/env bash
# Lots of applications don't respect XDG conventions
# so here are a bunch of hacks to get them working

# Set all the XDG path vars
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
# Shouldn't set this as systemd sets it up
#export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$UID}
export XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg}

# Set all the XDG paths for software in use
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
alias wget="wget --hsts-file=\"${XDG_CACHE_HOME}/wget/hsts\""

# This causes dumb issues with client connection to this box
# export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export XINITRC="${XDG_CONFIG_HOME}/X11/xinitrc"
export XSERVERRC="${XDG_CONFIG_HOME}/X11/xserverrc"

export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"

export ICEAUTHORITY="${XDG_CONFIG_HOME}/ICEauthority"

export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"

export SUBVERSION_HOME="${XDG_CONFIG_HOME}/subversion"

export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

export PYTHONHISTORY="${XDG_CACHE_HOME}/python/python_history"

